/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/*import java.security.MessageDigest;learnnnnnnnnnnnnnnnnn
import java.sql.DriverManager;*/
import java.sql.SQLException;
import javax.swing.JOptionPane;



/**
 *
 * @author Acer
 */
public class LOGIN_PAGE extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form LOGIN_PAGE
     */
    public LOGIN_PAGE() {
        initComponents();
        
        con = javaConnect.connectdb();
        /*setSize(1260, 840); // size problem
        setLocationRelativeTo(null);*/
        
        //display the login image here
        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_page_img.png")));
        username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username_img1.png")));
        password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password_img.png")));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png")));
        mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mini.png")));
        //center the form
        this.setLocationRelativeTo(null);
        //border to the title
        Border title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.BLACK);
        Login_Title.setBorder(title_border);
        
        
    }
        /*private String md5(char[] c){
            try{
                MessageDigest digs = MessageDigest.getInstance("MD5");
                digs.update((new String(c)).getBytes("UTF8"));
                String dodo = new String(digs.digest()); 
                return dodo;
            }catch(Exception e){
                return "";
            }
        }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Image = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Login_Title = new javax.swing.JLabel();
        password_icon = new javax.swing.JLabel();
        username_icon = new javax.swing.JLabel();
        username_text = new javax.swing.JTextField();
        password_text = new javax.swing.JPasswordField();
        log_into = new javax.swing.JButton();
        cancel_login = new javax.swing.JButton();
        mini = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        user_level = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setUndecorated(true);

        jLabel_Image.setForeground(new java.awt.Color(255, 204, 204));
        jLabel_Image.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        Login_Title.setFont(new java.awt.Font("Haettenschweiler", 0, 36)); // NOI18N
        Login_Title.setForeground(new java.awt.Color(102, 0, 102));
        Login_Title.setText("LOGIN");

        password_icon.setBackground(new java.awt.Color(255, 255, 255));
        password_icon.setOpaque(true);

        username_icon.setBackground(new java.awt.Color(255, 255, 255));
        username_icon.setOpaque(true);

        username_text.setForeground(new java.awt.Color(153, 153, 153));
        username_text.setText("username");
        username_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_textFocusLost(evt);
            }
        });
        username_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textActionPerformed(evt);
            }
        });

        password_text.setForeground(new java.awt.Color(153, 153, 153));
        password_text.setText("mypassword");
        password_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_textFocusLost(evt);
            }
        });

        log_into.setBackground(new java.awt.Color(51, 51, 255));
        log_into.setFont(new java.awt.Font("Arial", 1, 19)); // NOI18N
        log_into.setForeground(new java.awt.Color(0, 0, 0));
        log_into.setText("Log In");
        log_into.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_intoActionPerformed(evt);
            }
        });

        cancel_login.setBackground(new java.awt.Color(255, 51, 51));
        cancel_login.setFont(new java.awt.Font("Arial", 1, 19)); // NOI18N
        cancel_login.setForeground(new java.awt.Color(0, 0, 0));
        cancel_login.setText("Cancel");
        cancel_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_loginActionPerformed(evt);
            }
        });

        mini.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mini.setForeground(new java.awt.Color(0, 0, 0));
        mini.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mini.setToolTipText("");
        mini.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
        });

        close.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(0, 0, 0));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                closeVetoableChange(evt);
            }
        });

        user_level.setEditable(true);
        user_level.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        user_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "staff" }));
        user_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_levelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(username_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(password_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(Login_Title)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(mini, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(log_into, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(user_level, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(mini, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(username_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Login_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(user_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log_into)
                    .addComponent(cancel_login))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_textActionPerformed

    private void log_intoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_intoActionPerformed
        // Login to admin page or the staff page
        
        try{
           String main = "SELECT * FROM NBUSER.LOGINMAIN WHERE USERNAME=? AND PASSWORD=? AND USERTYPE=?";
           ps=con.prepareStatement(main);
           ps.setString(1, username_text.getText());
           ps.setString(2, password_text.getText());
           ps.setString(3, String.valueOf(user_level.getSelectedItem()));//usertype should be string type
           rs = ps.executeQuery();
           
           if(rs.next()){
                if(user_level.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Login Success!!\n\nWelcome to The Cinema System Admin Page");
                dispose(); 
                AdminHomepage adminHome = new AdminHomepage();
                adminHome.setVisible(true); 
                this.setVisible(false);
                
                
                }
                else if(user_level.getSelectedIndex()==1){
                JOptionPane.showMessageDialog(null, "Login Success!!\n\nWelcome to The Cinema System Staff Page");
                dispose(); 
                StaffHomepage staffScreen = new StaffHomepage();
                staffScreen.setVisible(true);
                this.setVisible(false);
                
                }
           }else{
                JOptionPane.showMessageDialog(null, "Login Fail!\n\nPlz Contact Support!!");
                }      
        }catch(SQLException sqe){
            JOptionPane.showMessageDialog(null, "Invalid Credentials!Back-OFF!"+sqe); 
        }
        
    }//GEN-LAST:event_log_intoActionPerformed

    /*FOCUS GAINED --------------------------USERNAME----------------------------------------*/
    private void username_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_textFocusGained
        //remove the text from the text field(background)
        //if the text field = "username" =>
        if(username_text.getText().trim().toLowerCase().equals("username")){
            username_text.setText("");//make sure to make("") with no space like(" ") as it wont display the username
            //change the text field color to black
            username_text.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_username_textFocusGained
    /*FOCUS LOST --------------------------USERNAME----------------------------------------*/
    private void username_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_textFocusLost
        // if the text field is empty -> set it to 'username'=>
        if(username_text.getText().trim().equals("") || username_text.getText().trim().equals("username")){
            username_text.setText("username");
            username_text.setForeground(new Color(155,153,153));
        }
    }//GEN-LAST:event_username_textFocusLost
    /*FOCUS GAINED --------------------------PASSWORD----------------------------------------*/
    private void password_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_textFocusGained
        // remove the text from the text field(background)
        //if the text field = "password" =>
        String password = String.valueOf(password_text.getPassword());
        if (password.trim().toLowerCase().equals("mypassword")){
            password_text.setText("");
            password_text.setForeground(Color.BLACK);
            //.equals password/<name> must be equal to the text inside the textfield for it to work
        }       
    }//GEN-LAST:event_password_textFocusGained
    /*FOCUS LOST --------------------------PASSWORD----------------------------------------*/
    private void password_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_textFocusLost
        // if the password is empty set it to 'password'
        String password = String.valueOf(password_text.getPassword());
        if(password.trim().equals("") || password.trim().toLowerCase().equals("mypassword")){
            password_text.setText("mypassword");
            password_text.setForeground(new Color(155,153,153));
        }
    }//GEN-LAST:event_password_textFocusLost

    private void cancel_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_loginActionPerformed
        // exit the program
        System.exit(0);
    }//GEN-LAST:event_cancel_loginActionPerformed

    private void closeVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_closeVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_closeVetoableChange
/*---------------x------------------------------------------------------------------x------------------*/
    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_miniMouseClicked

    private void user_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_levelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_PAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_Title;
    private javax.swing.JButton cancel_login;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton log_into;
    private javax.swing.JLabel mini;
    private javax.swing.JLabel password_icon;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JComboBox<String> user_level;
    private javax.swing.JLabel username_icon;
    private javax.swing.JTextField username_text;
    // End of variables declaration//GEN-END:variables
}
